/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// DeviceAttributeListTypeApplyConfiguration represents a declarative configuration of the DeviceAttributeListType type for use
// with apply.
//
// DeviceAttributeListType contains exactly one non-empty list of attribute values for use as a DeviceAttribute.
type DeviceAttributeListTypeApplyConfiguration struct {
	// IntValues is a list of numbers.
	IntValues []int64 `json:"ints,omitempty"`
	// BoolValues is a list of true/false values.
	BoolValues []bool `json:"bools,omitempty"`
	// StringValues is a list of strings.
	// Each string must not be longer than 64 characters.
	StringValues []string `json:"strings,omitempty"`
	// VersionValues is a list of semantic versions according to semver.org spec 2.0.0.
	// Each version string must not be longer than 64 characters.
	VersionValues []string `json:"versions,omitempty"`
}

// DeviceAttributeListTypeApplyConfiguration constructs a declarative configuration of the DeviceAttributeListType type for use with
// apply.
func DeviceAttributeListType() *DeviceAttributeListTypeApplyConfiguration {
	return &DeviceAttributeListTypeApplyConfiguration{}
}

// WithIntValues adds the given value to the IntValues field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the IntValues field.
func (b *DeviceAttributeListTypeApplyConfiguration) WithIntValues(values ...int64) *DeviceAttributeListTypeApplyConfiguration {
	for i := range values {
		b.IntValues = append(b.IntValues, values[i])
	}
	return b
}

// WithBoolValues adds the given value to the BoolValues field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the BoolValues field.
func (b *DeviceAttributeListTypeApplyConfiguration) WithBoolValues(values ...bool) *DeviceAttributeListTypeApplyConfiguration {
	for i := range values {
		b.BoolValues = append(b.BoolValues, values[i])
	}
	return b
}

// WithStringValues adds the given value to the StringValues field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the StringValues field.
func (b *DeviceAttributeListTypeApplyConfiguration) WithStringValues(values ...string) *DeviceAttributeListTypeApplyConfiguration {
	for i := range values {
		b.StringValues = append(b.StringValues, values[i])
	}
	return b
}

// WithVersionValues adds the given value to the VersionValues field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the VersionValues field.
func (b *DeviceAttributeListTypeApplyConfiguration) WithVersionValues(values ...string) *DeviceAttributeListTypeApplyConfiguration {
	for i := range values {
		b.VersionValues = append(b.VersionValues, values[i])
	}
	return b
}
